# Generated by Django 5.2.5 on 2025-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('strap_material', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
