# Generated by Django 5.2.6 on 2025-11-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0003_watch_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Added'), ('update', 'Updated')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_app.watch')),
            ],
        ),
    ]
