# Generated by Django 5.2.6 on 2025-11-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0004_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('add', 'Added'), ('update', 'Updated'), ('login', 'Login')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_app.watch'),
        ),
    ]
