# Generated by Django 5.2.6 on 2025-11-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0005_activity_user_alter_activity_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('add', 'Added'), ('update', 'Updated')], max_length=20),
        ),
    ]
